### PR TITLE
Add k_aug build

### PR DESCRIPTION
**Pull request by eslickj**
This is an update to add the k_aug build to the IDAES solvers build.  I put a simplified CMake file here that I just copy over the current k_aug Cmake file.  It's not a general purpose file.  It assumes you are following up on our specific Ipopt build.  We'll probably want to find a more long-term solution by refining the build in setup in the k_aug repo.

I'll start building binaries now, and post them when this is approved.  If any review wants to preview the binary tarball before approving, just let me know.

As usual, I still don't have the ability to do OSX builds.

### CODE REVIEW

**Review by jsiirola — APPROVED** [review]
This looks good to me.

**Comment by eslickj** [comment]
@jsiirola, thanks.  Of course, now that I moved to do the real builds, Ipopt isn't building again.  Every time I build these there is some new change.  Hopefully I'll have the binaries in a few hours.  I may need to make some tweaks in this PR to get things working right again.

**Comment by eslickj** [comment]
The mumps building issue appears to be this one https://bugs.gentoo.org/727356.

**Comment by eslickj** [comment]
@jsiirola, I seem to have a problem with the Pynumero CMake setup.  It's set to compile the Pynumero HSL stuff if it finds the HSL libraries.  I have the HSL libraries, but don't want to compile it.  That's fine, I ignore the extra files.  The problem is that there is a linking error, since we are missing "-lgfortran".  This also wasn't a problem until now, because I didn't want the HSL stuff anyway.  My issue now is that it is trying to link the HSL stuff before building the ASL stuff and failing and terminating before building the ASL stuff.

Is there are we can say DONT_BUILD_MA27_I_REALLY_MEAN_IT_I_DONT_CARE_IF_YOU_FOUND_HSL,  or alternatively fixing the gfortran linking?  I'm looking for something easy and fast where I don't have to edit the cmake file or wait for a Pyomo update.

**Comment by jsiirola** [comment]
You should be able to `-DBUILD_MA57=no` on the `cmake` / `ccmake` command line to disable ma57 entirely.

**Comment by eslickj** [comment]
@jsiirola the problem is with ma27 (at least the first problem).  Still not sure where the ASL build went, since it usually comes out first.

```
Cloning into 'pyomo'...
Updating files: 100% (5752/5752), done.
Already on 'master'
Your branch is up to date with 'origin/master'.
-- The C compiler identification is GNU 10.1.0
-- The CXX compiler identification is GNU 10.1.0
-- Check for working C compiler: C:/msys64/mingw64/bin/gcc.exe
-- Check for working C compiler: C:/msys64/mingw64/bin/gcc.exe - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/msys64/mingw64/bin/g++.exe
-- Check for working CXX compiler: C:/msys64/mingw64/bin/g++.exe - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: C:/msys64/mingw64/bin/pkg-config.exe (found version "0.29.2")
-- Configuring done
-- Generating done
-- Build files have been written to: C:/repo/idaes-ext/pyomo/pyomo/contrib/pynumero/src/build
Scanning dependencies of target pynumero_MA27
[ 16%] Building CXX object CMakeFiles/pynumero_MA27.dir/ma27Interface.cpp.obj
[ 33%] Linking CXX shared library libpynumero_MA27.dll
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/repo/idaes-ext/coinbrew/dist/lib/libcoinhsl.a(ma27d.o):ma27d.f:(.text+0x1d16): undefined reference to `_gfortran_st_write'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/repo/idaes-ext/coinbrew/dist/lib/libcoinhsl.a(ma27d.o):ma27d.f:(.text+0x1d2c): undefined reference to `_gfortran_transfer_integer_write'
```

**Comment by eslickj** [comment]
@jsiirola  Misread you answer.  I'll give that a shot.

**Comment by jsiirola** [comment]
@eslickj I am not sure that my answer actually works.  At least, I am still seeing that MA27 is being built even when I set it manually.  Working the issue now.

**Comment by jsiirola** [comment]
Try the following patch, and then `-DENABLE_HSL=no` should prevent building ma27:
```diff
diff --git a/pyomo/contrib/pynumero/src/CMakeLists.txt b/pyomo/contrib/pynumero/src/CMakeLists.txt
index 001e131..b13bc6a 100644
--- a/pyomo/contrib/pynumero/src/CMakeLists.txt
+++ b/pyomo/contrib/pynumero/src/CMakeLists.txt
@@ -11,6 +11,7 @@ include(ExternalProject)
 OPTION(BUILD_ASL "Build the PyNumero ASL interface" ON)
 OPTION(BUILD_MA27 "Build the PyNumero ma27 interface" OFF)
 OPTION(BUILD_MA57 "Build the PyNumero ma57 interface" OFF)
+OPTION(ENABLE_HSL "Enable the HSL library interfaces" ON)
 
 # Dependencies that we manage / can install
 SET(AMPLMP_TAG "3.1.0" CACHE STRING
@@ -98,6 +99,12 @@ IF( MA27_LIBRARY OR MA27_OBJECT )
     set_property(CACHE BUILD_MA27 PROPERTY VALUE ON)
 ENDIF()
 
+#...but if the HSL interface is not enabled, do not build the MA* libraries
+IF( NOT ENABLE_HSL )
+    set_property(CACHE BUILD_MA27 PROPERTY VALUE OFF)
+    set_property(CACHE BUILD_MA57 PROPERTY VALUE OFF)
+ENDIF()
+
 # If BUILD_AMPLMP_IF_NEEDED is set and we couldn't find / weren't
 # pointed to an ASL build, then we will forcibly enable the AMPLMP build
 # to provide the ASL.

```

**Comment by eslickj** [comment]
@jsiirola Alright it seems to work.  I'm adding the patching here to get it into the builds in docker containers.  If it fixes things we can take it back out once the fix is in Pyomo.

**Comment by jsiirola** [comment]
The PR is in the Pyomo review queue (Pyomo/pyomo#1632).  It should move through pretty quickly, likely merged by tonight.

**Comment by eslickj** [comment]
Okay, the windows build is working now.  I have an odd issue with -ldl, but that should be easy to sort out.

**Review by JanghoPark-LBL — APPROVED** [review]
I tested that build scripts work.  It looks good to me

**Comment by jsiirola** [comment]
The PR is in to Pyomo master.

**Comment by eslickj** [comment]
@jsiirola thanks, I'll pull the patch back out.  I had to add a few hacky work-arounds, but everything is working again.  Should have binaries soon.  Just need to hash them, test them and decide on a new release number.

**Review by jsiirola — APPROVED** [review]

**Pull request merged**
